create table passports(
  
 	id INT primary key GENERATED BY DEFAULT AS IDENTITY 
   (START WITH 100 INCREMENT BY 1),
  	nationality varchar(50)
);

insert into passports(nationality)
VALUES
	('N34FG21B'),
    ('K65LO4R7'),
    ('ZE657QP2');
    
    
    
create table people(

	id	serial primary key,
    first_name varchar(50),
    salary numeric(10, 2),
    passport_id INTEGER,
    
    constraint fk_people_passports
  		FOREIGN KEY(passport_id)
  		REFERENCES passports(id)


);

insert into people(first_name, salary, passport_id)
values
	('Roberto', 43300.0000, 101),
    ('Tom', 56100.0000, 102),
    ('Yana', 60200.0000, 100);
